export const indents = [
  {
    soId: "DO12345",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "29 July 2024",
    quantity: 25,
    approvalStatus: "Approved",
  },
  {
    soId: "DO12346",
    warehouseName: "Pace Industries",
    unloadingDateAndTime: "28 July 2024",
    quantity: 16,
    approvalStatus: "Pending",
  },
  {
    soId: "DO12347",
    warehouseName: "Rajeswari Industries",
    unloadingDateAndTime: "29 July 2022",
    quantity: 15,
    approvalStatus: "Approved",
  },
  {
    soId: "DO12348",
    warehouseName: "Pace Industries",
    unloadingDateAndTime: "30 July 2024",
    quantity: 10,
    approvalStatus: "Declined",
  },
  {
    soId: "DO12349",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "28 July 2024",
    quantity: 26,
    approvalStatus: "Declined",
  },
  {
    soId: "DO12353",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "29 July 2024",
    quantity: 20,
    approvalStatus: "Approved",
  },
  {
    soId: "DO12345",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "29 July 2024",
    quantity: 25,
    approvalStatus: "Approved",
  },
  {
    soId: "DO12346",
    warehouseName: "Pace Industries",
    unloadingDateAndTime: "28 July 2024",
    quantity: 16,
    approvalStatus: "Pending",
  },
  {
    soId: "DO12347",
    warehouseName: "Rajeswari Industries",
    unloadingDateAndTime: "29 July 2022",
    quantity: 15,
    approvalStatus: "Approved",
  },
  {
    soId: "DO12348",
    warehouseName: "Pace Industries",
    unloadingDateAndTime: "30 July 2024",
    quantity: 10,
    approvalStatus: "Declined",
  },
  {
    soId: "DO12349",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "28 July 2024",
    quantity: 26,
    approvalStatus: "Declined",
  },
  {
    soId: "DO12353",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "29 July 2024",
    quantity: 20,
    approvalStatus: "Pending",
  },
  {
    soId: "DO12353",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "29 July 2024",
    quantity: 20,
    approvalStatus: "Declined",
  },
  {
    soId: "DO12345",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "29 July 2024",
    quantity: 25,
    approvalStatus: "Approved",
  },
  {
    soId: "DO12346",
    warehouseName: "Pace Industries",
    unloadingDateAndTime: "28 July 2024",
    quantity: 16,
    approvalStatus: "Pending",
  },
  {
    soId: "DO12347",
    warehouseName: "Rajeswari Industries",
    unloadingDateAndTime: "29 July 2022",
    quantity: 15,
    approvalStatus: "Pending",
  },
  {
    soId: "DO12348",
    warehouseName: "Pace Industries",
    unloadingDateAndTime: "30 July 2024",
    quantity: 10,
    approvalStatus: "Declined",
  },
  {
    soId: "DO12349",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "28 June 2024",
    quantity: 26,
    approvalStatus: "Declined",
  },
  {
    soId: "DO12353",
    warehouseName: "Acme Industries",
    unloadingDateAndTime: "29 June 2024",
    quantity: 20,
    approvalStatus: "Approved",
  },
  {
    soId: "DO12346",
    warehouseName: "Pace Industries",
    unloadingDateAndTime: "28 July 2024",
    quantity: 16,
    approvalStatus: "Pending",
  },
  {
    soId: "DO12347",
    warehouseName: "Rajeswari Industries",
    unloadingDateAndTime: "29 July 2022",
    quantity: 15,
    approvalStatus: "Pending",
  },
  {
    soId: "DO12348",
    warehouseName: "Pace Industries",
    unloadingDateAndTime: "30 July 2024",
    quantity: 10,
    approvalStatus: "Declined",
  },
];
